apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: us.gcr.io/wkinfra-171623/xperscore/infrabot
    kaniko:
      buildContext:
        localDir: {}
      cache:
        repo: us.gcr.io/wkinfra-171623/xperscore/infrabot
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/xperscore/infrabot:{{.VERSION}}'
  cluster:
    pullSecretName: kaniko-secret
    namespace: jx
    dockerConfig:
      secretName: jenkins-docker-cfg
deploy:
  kubectl: {}