apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: '{{.DOCKER_REGISTRY}}/xperscore/infrabot'
    kaniko:
      buildContext:
        localDir: {}
      cache: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/xperscore/infrabot:{{.VERSION}}'